server:
  port: 8095

spring:
  application:
    name: rangiffler-userdata

  grpc:
    server:
      port: 8096
      enable-reflection: true

  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rangiffler-userdata
    locations: classpath:db/migration/rangiffler-userdata

logging:
  file:
    path: ./logs/rangiffler-userdata
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  kafka:
    bootstrap-servers: 'localhost:9092'
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3309/rangiffler-userdata?createDatabaseIfNotExist=true'
    username: root
    password: secret

---
spring:
  config:
    activate:
      on-profile: 'docker'
  kafka:
    bootstrap-servers: 'kafka:9092'
  datasource:
    url: 'jdbc:mysql://mysql-userdata:3306/rangiffler-userdata?createDatabaseIfNotExist=true'
    username: root
    password: secret