package guru.qa.rangiffler.defs;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Country {
  TG("tg", "Togo"),
  LA("la", "Lao People`s Democratic Republic"),
  MR("mr", "Mauritania"),
  NI("ni", "Nicaragua"),
  LV("lv", "Latvia"),
  OM("om", "Oman"),
  AF("af", "Afghanistan"),
  CY("cy", "Cyprus"),
  BJ("bj", "Benin"),
  AQ("aq", "Antarctica"),
  CN("cn", "China"),
  CO("co", "Colombia"),
  CX("cx", "Christmas Island"),
  AG("ag", "Antigua and Barbuda"),
  MS("ms", "Montserrat"),
  MD("md", "Moldova, Republic of"),
  ZM("zm", "Zambia"),
  VN("vn", "Viet Nam"),
  TF("tf", "French Southern Territories"),
  TD("td", "Chad"),
  YT("yt", "Mayotte"),
  LB("lb", "Lebanon"),
  LU("lu", "Luxembourg"),
  MQ("mq", "Martinique"),
  CZ("cz", "Czech Republic"),
  AE("ae", "United Arab Emirates"),
  CM("cm", "Cameroon"),
  BI("bi", "Burundi"),
  AR("ar", "Argentina"),
  AS("as", "American Samoa"),
  BH("bh", "Bahrain"),
  CL("cl", "Chile"),
  AD("ad", "Andorra"),
  MP("mp", "Northern Mariana Islands"),
  LT("lt", "Lithuania"),
  MG("mg", "Madagascar"),
  LC("lc", "Saint Lucia"),
  TR("tr", "Turkey"),
  UA("ua", "Ukraine"),
  TV("tv", "Tuvalu"),
  VI("vi", "Virgin Islands, U.S."),
  MT("mt", "Malta"),
  NO("no", "Norway"),
  MC("mc", "Monaco"),
  CH("ch", "Switzerland"),
  AW("aw", "Aruba"),
  BZ("bz", "Belize"),
  BM("bm", "Bermuda"),
  CI("ci", "Cote D`Ivoire"),
  MU("mu", "Mauritius"),
  US("us", "United States"),
  TW("tw", "Taiwan, Province of China"),
  YE("ye", "Yemen"),
  MW("mw", "Malawi"),
  NL("nl", "Netherlands"),
  LS("ls", "Lesotho"),
  BO("bo", "Bolivia"),
  AT("at", "Austria"),
  CK("ck", "Cook Islands"),
  BY("by", "Belarus"),
  AU("au", "Australia"),
  BN("bn", "Brunei Darussalam"),
  MA("ma", "Morocco"),
  NZ("nz", "New Zealand"),
  LR("lr", "Liberia"),
  MV("mv", "Maldives"),
  TC("tc", "Turks and Caicos Islands"),
  UG("ug", "Uganda"),
  TT("tt", "Trinidad and Tobago"),
  PL("pl", "Poland"),
  IN("in", "India"),
  GE("ge", "Georgia"),
  GR("gr", "Greece"),
  GS("gs", "South Georgia and the South Sandwich Islands"),
  GD("gd", "Grenada"),
  IO("io", "British Indian Ocean Territory"),
  HK("hk", "Hong Kong"),
  KP("kp", "Korea, Democratic People`s Republic of"),
  KG("kg", "Kyrgyzstan"),
  PM("pm", "Saint Pierre and Miquelon"),
  SV("sv", "El Salvador"),
  RE("re", "Reunion"),
  SA("sa", "Saudi Arabia"),
  SC("sc", "Seychelles"),
  ST("st", "Sao Tome and Principe"),
  KE("ke", "Kenya"),
  KR("kr", "Korea, Republic of"),
  GF("gf", "French Guiana"),
  DJ("dj", "Djibouti"),
  GQ("gq", "Equatorial Guinea"),
  GP("gp", "Guadeloupe"),
  DK("dk", "Denmark"),
  IL("il", "Israel"),
  PN("pn", "Pitcairn"),
  SB("sb", "Solomon Islands"),
  PY("py", "Paraguay"),
  RU("ru", "Russian Federation"),
  KW("kw", "Kuwait"),
  DO("do", "Dominican Republic"),
  GT("gt", "Guatemala"),
  GB("gb", "United Kingdom"),
  GU("gu", "Guam"),
  HM("hm", "Heard Island and Mcdonald Islands"),
  SG("sg", "Singapore"),
  PK("pk", "Pakistan"),
  SR("sr", "Suriname"),
  SE("se", "Sweden"),
  JP("jp", "Japan"),
  GW("gw", "Guinea-Bissau"),
  EH("eh", "Western Sahara"),
  DZ("dz", "Algeria"),
  GA("ga", "Gabon"),
  FR("fr", "France"),
  DM("dm", "Dominica"),
  HN("hn", "Honduras"),
  SD("sd", "Sudan"),
  RW("rw", "Rwanda"),
  PH("ph", "Philippines"),
  QA("qa", "Qatar"),
  PE("pe", "Peru"),
  PR("pr", "Puerto Rico"),
  SI("si", "Slovenia"),
  HT("ht", "Haiti"),
  ES("es", "Spain"),
  GL("gl", "Greenland"),
  GM("gm", "Gambia"),
  ER("er", "Eritrea"),
  FI("fi", "Finland"),
  EE("ee", "Estonia"),
  KN("kn", "Saint Kitts and Nevis"),
  HU("hu", "Hungary"),
  IQ("iq", "Iraq"),
  KY("ky", "Cayman Islands"),
  SH("sh", "Saint Helena"),
  PS("ps", "Palestinian Territory, Occupied"),
  PF("pf", "French Polynesia"),
  SJ("sj", "Svalbard and Jan Mayen"),
  ID("id", "Indonesia"),
  IS("is", "Iceland"),
  EG("eg", "Egypt"),
  FK("fk", "Falkland Islands (Malvinas)"),
  FJ("fj", "Fiji"),
  GN("gn", "Guinea"),
  GY("gy", "Guyana"),
  IR("ir", "Iran, Islamic Republic of"),
  KM("km", "Comoros"),
  IE("ie", "Ireland"),
  KZ("kz", "Kazakhstan"),
  RO("ro", "Romania"),
  SK("sk", "Slovakia"),
  PG("pg", "Papua New Guinea"),
  PT("pt", "Portugal"),
  SO("so", "Somalia"),
  HR("hr", "Croatia"),
  KI("ki", "Kiribati"),
  JM("jm", "Jamaica"),
  EC("ec", "Ecuador"),
  ET("et", "Ethiopia"),
  FO("fo", "Faroe Islands"),
  KH("kh", "Cambodia"),
  SY("sy", "Syrian Arab Republic"),
  SN("sn", "Senegal"),
  PW("pw", "Palau"),
  SL("sl", "Sierra Leone"),
  FM("fm", "Micronesia, Federated States of"),
  GI("gi", "Gibraltar"),
  DE("de", "Germany"),
  GH("gh", "Ghana"),
  JO("jo", "Jordan"),
  IT("it", "Italy"),
  PA("pa", "Panama"),
  SZ("sz", "Swaziland"),
  SM("sm", "San Marino"),
  TN("tn", "Tunisia"),
  ML("ml", "Mali"),
  CG("cg", "Congo"),
  AO("ao", "Angola"),
  BT("bt", "Bhutan"),
  AN("an", "Netherlands Antilles"),
  BB("bb", "Barbados"),
  CF("cf", "Central African Republic"),
  MM("mm", "Myanmar"),
  LI("li", "Liechtenstein"),
  NA("na", "Namibia"),
  MZ("mz", "Mozambique"),
  TO("to", "Tonga"),
  VG("vg", "Virgin Islands, British"),
  VE("ve", "Venezuela"),
  TZ("tz", "Tanzania, United Republic of"),
  TM("tm", "Turkmenistan"),
  MX("mx", "Mexico"),
  NC("nc", "New Caledonia"),
  MO("mo", "Macao"),
  LK("lk", "Sri Lanka"),
  CD("cd", "Congo, the Democratic Republic of the"),
  AL("al", "Albania"),
  BW("bw", "Botswana"),
  CR("cr", "Costa Rica"),
  BV("bv", "Bouvet Island"),
  AM("am", "Armenia"),
  AZ("az", "Azerbaijan"),
  BA("ba", "Bosnia and Herzegovina"),
  MN("mn", "Mongolia"),
  NU("nu", "Niue"),
  MY("my", "Malaysia"),
  TL("tl", "Timor-Leste"),
  WS("ws", "Samoa"),
  TH("th", "Thailand"),
  NF("nf", "Norfolk Island"),
  LY("ly", "Libyan Arab Jamahiriya"),
  AI("ai", "Anguilla"),
  BR("br", "Brazil"),
  CV("cv", "Cape Verde"),
  BE("be", "Belgium"),
  CA("ca", "Canada"),
  BD("bd", "Bangladesh"),
  BS("bs", "Bahamas"),
  NG("ng", "Nigeria"),
  MK("mk", "Macedonia, the Former Yugoslav Republic of"),
  NP("np", "Nepal"),
  VA("va", "Holy See (Vatican City State"),
  UZ("uz", "Uzbekistan"),
  UM("um", "United States Minor Outlying Islands"),
  TK("tk", "Tokelau"),
  VC("vc", "Saint Vincent and the Grenadines"),
  ZW("zw", "Zimbabwe"),
  NR("nr", "Nauru"),
  NE("ne", "Niger"),
  CU("cu", "Cuba"),
  BF("bf", "Burkina Faso"),
  BG("bg", "Bulgaria"),
  CC("cc", "Cocos (Keeling) Islands"),
  MH("mh", "Marshall Islands"),
  ZA("za", "South Africa"),
  UY("uy", "Uruguay"),
  WF("wf", "Wallis and Futuna"),
  VU("vu", "Vanuatu"),
  TJ("tj", "Tajikistan");

  private final String code;
  private final String fullName;

  public static Country fromCode(String code) {
    for (Country c : values()) {
      if (c.code.equalsIgnoreCase(code)) {
        return c;
      }
    }
    throw new IllegalArgumentException("Unknown country code: " + code);
  }

  public static Country fromName(String name) {
    for (Country c : values()) {
      if (c.fullName.equalsIgnoreCase(name)) {
        return c;
      }
    }
    throw new IllegalArgumentException("Unknown country name: " + name);
  }
}
